export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_FAIL='LOGOUT_FAIL';
export const SET_REDIRECT_PATH='SET_REDIRECT_PATH';
export const DELETE_ERROR_REOPRT='DELETE_ERROR_REOPRT';

export const LOAD_USER_INFO_SUC='LOAD_USER_INFO_SUC';
export const LOAD_USER_INFO_FAIL ='LOAD_USER_INFO_FAIL';

export const GET_CLICKED_USER_INFO_Fail = "GET_CLICKED_USER_INFO_Fail";
export const GET_CLICKED_USER_INFO_SUC = "GET_CLICKED_USER_INFO_SUC"